<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<StaticWebAssetBasePath>/</StaticWebAssetBasePath>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>Umbraco.Community.Forms.Intl_Tel_Input</PackageId>
		<Product>Umbraco.Community.Forms.Intl_Tel_Input</Product>
		<Title>Umbraco.Community.Forms.Intl_Tel_Input</Title>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>Umbraco.Community.Forms.Intl_Tel_Input</PackageId>
		<Product>Umbraco.Community.Forms.Intl_Tel_Input</Product>
		<Title>Umbraco.Community.Forms.Intl_Tel_Input</Title>
		<RootNamespace>Umbraco.Community.Forms.Intl_Tel_Input</RootNamespace>
		<Description>Add the Intl-Tel-Input text field to your Umbraco Forms for Umbraco V15+</Description>
		<PackageTags>umbraco;umbraco-cms;intl;international;telephone;input;intl-tel-input;umbraco-marketplace;</PackageTags>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<Authors>Aaron Sadler; UmbHost Limited</Authors>
		<Copyright>© $([System.DateTime]::Now.ToString(`yyyy`)) UmbHost Limited</Copyright>
		<PackageProjectUrl>https://github.com/UmbHost/Umbraco.Community.Forms.uCaptcha</PackageProjectUrl>
		<RepositoryUrl>https://github.com/UmbHost/Umbraco.Community.Forms.uCaptcha</RepositoryUrl>
		<PackageIcon>intl_tel_input_logo.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<AssemblyVersion>6.0.0.0</AssemblyVersion>
		<FileVersion>6.0.0.0</FileVersion>
		<VersionPrefix>6.0.0</VersionPrefix>
	</PropertyGroup>


	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="libphonenumber-csharp" Version="9.0.15" />
		<PackageReference Include="Umbraco.Cms.Web.Website" Version="16.2.0" />
		<PackageReference Include="Umbraco.Cms.Web.Common" Version="16.2.0" />
		<PackageReference Include="Umbraco.Cms.Api.Common" Version="16.2.0" />
		<PackageReference Include="Umbraco.Cms.Api.Management" Version="16.2.0" />
		<PackageReference Include="Umbraco.Forms.Core" Version="16.1.0" />
		<PackageReference Include="Umbraco.Forms.Web" Version="16.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ClientAssetsInputs Include="Client\**" Exclude="$(DefaultItemExcludes)" />

		<!-- Dont include the client folder as part of packaging nuget build -->
		<Content Remove="Client\**" />

		<!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
		<None Include="Client\public\umbraco-package.json" Pack="false" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\" />
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\intl_tel_input_logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
</Project>
